default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  host: db
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

development:
  <<: *default
  database: db/rh-setelia_dev

production:
  <<: *default
  database: db/rh-setelia_prod
